import { formatGregorianDate, formatGregorianDateTime } from "@shared/dateFormat";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { UserPlus, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function CustomersPage() {
  const utils = trpc.useUtils();
  const customers = trpc.customers.list.useQuery();
  const [form, setForm] = useState({ fullName: "", identityNumber: "", phone: "" });
  const create = trpc.customers.create.useMutation({ onSuccess: async () => { setForm({ fullName: "", identityNumber: "", phone: "" }); await utils.customers.list.invalidate(); toast.success("تمت إضافة العميل إلى القائمة"); }, onError: (error) => toast.error(error.message) });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.fullName.trim() || !form.identityNumber.trim() || !form.phone.trim()) return toast.error("أدخل اسم العميل ورقم الهوية والجوال"); create.mutate(form); };

  return <DashboardLayout><div dir="rtl" className="mx-auto max-w-5xl space-y-5"><div><p className="mb-1 text-xs font-bold text-[#139f95]">دليل العملاء</p><h1 className="text-2xl font-black tracking-tight">العملاء</h1><p className="mt-1 text-sm text-slate-500">اضغط اسم العميل لفتح ملفه وكشف عملياته وطباعته لجميع العقود أو لعقد واحد.</p></div><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UserPlus className="h-5 w-5 text-[#139f95]" />إضافة عميل جديد</CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold text-slate-700">الاسم الكامل<Input required value={form.fullName} onChange={(event) => update("fullName", event.target.value)} className="mt-2 min-h-12" /></label><label className="text-sm font-semibold text-slate-700">رقم الهوية<Input required value={form.identityNumber} onChange={(event) => update("identityNumber", event.target.value)} className="mt-2 min-h-12" /></label><label className="text-sm font-semibold text-slate-700">رقم الجوال الأساسي <span className="mr-1 text-red-500" aria-hidden="true">*</span><Input required type="tel" inputMode="tel" autoComplete="tel" value={form.phone} onChange={(event) => update("phone", event.target.value)} className="mt-2 min-h-12" /></label><Button type="submit" disabled={create.isPending} className="min-h-12 bg-[#13a99f] font-bold hover:bg-[#0d938b] sm:col-span-3">{create.isPending ? "جارٍ الحفظ..." : "حفظ وإضافة للقائمة"}</Button></form></CardContent></Card><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Users className="h-5 w-5 text-[#0b2747]" />قائمة العملاء <span className="text-sm font-normal text-slate-400">({customers.data?.length ?? 0})</span></CardTitle></CardHeader><CardContent>{customers.isLoading ? <p className="py-10 text-center text-sm text-slate-400">جارٍ تحميل العملاء...</p> : customers.error ? <p className="py-10 text-center text-sm text-red-600">تعذر تحميل العملاء: {customers.error.message}</p> : <div className="overflow-x-auto overscroll-x-contain"><table className="w-full min-w-[620px] text-right text-sm"><caption className="sr-only">قائمة العملاء</caption><thead><tr className="border-b border-slate-100 text-xs text-slate-400"><th className="p-4">الاسم</th><th className="p-4">الهوية</th><th className="p-4">الجوال</th><th className="p-4">تاريخ الإضافة</th></tr></thead><tbody>{customers.data?.map((customer) => <tr key={customer.id} className="border-b border-slate-50"><td className="p-4 font-semibold"><Link href={`/customers/${customer.id}`} className="text-[#0c8f87] underline-offset-4 hover:underline">{customer.fullName}</Link></td><td className="p-4">{customer.identityNumber}</td><td className="p-4">{customer.phone}</td><td className="p-4">{formatGregorianDate(customer.createdAt)}</td></tr>)}</tbody></table></div>}</CardContent></Card></div></DashboardLayout>;
}
