import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { isOtherRevenueReason, paymentReasonLabels, paymentReasonOptions, type PaymentReason } from "@shared/paymentReasons";
import { ArrowLeftRight, Banknote, CarFront, CirclePause, CircleStop, RotateCcw, TimerReset } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";
import { allocatePayment } from "../../../shared/paymentAllocation";
import { calculateCloseSettlement } from "../../../shared/closeSettlement";
import { calculateSuspensionSettlement } from "../../../shared/suspensionSettlement";
import { suspensionReasonLabels, suspensionReasonOptions, type SuspensionReason } from "../../../shared/suspensionReasons";
type Operation = "payment" | "additional_fee" | "extension" | "vehicle_swap" | "suspend" | "close" | "return";
const operationCards: Array<{ value: Exclude<Operation, "additional_fee">; label: string; icon: typeof Banknote }> = [
  { value: "payment", label: "استلام مبلغ", icon: Banknote },
  { value: "extension", label: "تمديد", icon: TimerReset },
  { value: "vehicle_swap", label: "تبديل السيارة", icon: ArrowLeftRight },
  { value: "suspend", label: "تعليق للتعثر", icon: CirclePause },
  { value: "close", label: "إغلاق العقد", icon: CircleStop },
  { value: "return", label: "استرجاع السيارة", icon: RotateCcw },
];

type PaymentMethod = "cash" | "network" | "transfer" | "mixed";
const empty = "";

export default function ContractOperationsPanel() {
  const [location] = useLocation();
  const utils = trpc.useUtils();
  const [contractNumber, setContractNumber] = useState(empty);
  const [operation, setOperation] = useState<Operation>("payment");
  const [amount, setAmount] = useState(empty);
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>("cash");
  const [paymentFirstMethod, setPaymentFirstMethod] = useState<Exclude<PaymentMethod, "mixed">>("cash");
  const [paymentSecondMethod, setPaymentSecondMethod] = useState<Exclude<PaymentMethod, "mixed">>("network");
  const [cashAmount, setCashAmount] = useState(empty);
  const [networkAmount, setNetworkAmount] = useState(empty);
  const [paymentReason, setPaymentReason] = useState<PaymentReason>("extra_km");
  const [paymentException, setPaymentException] = useState<"none" | "suspended_contract" | "justified_non_suspended">("none");
  const [exceptionReason, setExceptionReason] = useState(empty);
  const [suspensionReason, setSuspensionReason] = useState<SuspensionReason>("financial_default");
  const [followUpDate, setFollowUpDate] = useState(empty);
  const [extensionDays, setExtensionDays] = useState(empty);
  const [extensionPaymentAmount, setExtensionPaymentAmount] = useState(empty);
  const [extensionPaymentMethod, setExtensionPaymentMethod] = useState<PaymentMethod>("cash");
  const [extensionPaymentCashAmount, setExtensionPaymentCashAmount] = useState(empty);
  const [extensionPaymentNetworkAmount, setExtensionPaymentNetworkAmount] = useState(empty);
  const [vehicleId, setVehicleId] = useState(empty);
  const [details, setDetails] = useState(empty);
  const [vehicleMileage, setVehicleMileage] = useState(empty);
  const vehicles = trpc.vehicles.available.useQuery();
  const contracts = trpc.contracts.list.useQuery();
  const selectedContractRow = useMemo(() => contracts.data?.find((item) => item.contract.contractNumber === contractNumber.trim()), [contracts.data, contractNumber]);
  const selectedContract = selectedContractRow?.contract;
  const remaining = selectedContractRow ? Number(selectedContractRow.grandOutstanding) : null;
  const previousOutstanding = selectedContractRow ? Number(selectedContractRow.previousOutstanding) : 0;
  const currentCharge = selectedContractRow ? Number(selectedContractRow.currentOutstanding) : 0;
  const excessMileageOutstanding = selectedContractRow ? Number(selectedContractRow.excessMileageOutstanding ?? 0) : 0;
  const suspendedOutstanding = useMemo(() => (contracts.data ?? []).filter((item) => item.contract.status === "suspended").reduce((sum, item) => sum + Number(item.grandOutstanding ?? 0), 0), [contracts.data]);
  const paymentTotal = paymentMethod === "mixed" ? (Number(cashAmount) || 0) + (Number(networkAmount) || 0) : Number(amount) || 0;
  const extensionPaymentTotal = extensionPaymentMethod === "mixed" ? (Number(extensionPaymentCashAmount) || 0) + (Number(extensionPaymentNetworkAmount) || 0) : Number(extensionPaymentAmount) || 0;
  const allocation = operation === "payment" && paymentTotal > 0 && selectedContract && !isOtherRevenueReason(paymentReason) ? allocatePayment({ paymentAmount: paymentTotal, previousOutstanding, currentOutstanding: currentCharge, excessMileageOutstanding }) : null;
  const extensionAllocation = operation === "extension" && extensionPaymentTotal > 0 && selectedContract ? allocatePayment({ paymentAmount: extensionPaymentTotal, previousOutstanding, currentOutstanding: currentCharge, excessMileageOutstanding }) : null;
  const requiresMileage = ["vehicle_swap", "close", "return", "suspend"].includes(operation);
  const closePreview = operation === "close" && selectedContract ? calculateCloseSettlement({ baseTotal: selectedContract.totalAmount, expectedReturnDate: selectedContract.expectedReturnDate, closedAt: new Date(), rentalAmount: selectedContract.rentalAmount, type: selectedContract.type, paidAmount: selectedContract.paidAmount, excessMileageBalance: selectedContract.excessMileageAmount }) : null;
  const suspensionPreview = operation === "suspend" && selectedContract ? calculateSuspensionSettlement({ baseTotal: selectedContract.totalAmount, expectedReturnDate: selectedContract.expectedReturnDate, suspendedAt: new Date(), rentalAmount: selectedContract.rentalAmount, type: selectedContract.type, paidAmount: selectedContract.paidAmount, excessMileageBalance: selectedContract.excessMileageAmount }) : null;
  const resetForm = () => { setAmount(empty); setCashAmount(empty); setNetworkAmount(empty); setExtensionDays(empty); setExtensionPaymentAmount(empty); setExtensionPaymentCashAmount(empty); setExtensionPaymentNetworkAmount(empty); setVehicleId(empty); setVehicleMileage(empty); setDetails(empty); setFollowUpDate(empty); setPaymentException("none"); setExceptionReason(empty); };
  const record = trpc.operations.record.useMutation({ onSuccess: async () => { toast.success("تم حفظ العملية وتحديث السجل"); resetForm(); await Promise.all([utils.contracts.list.invalidate(), utils.vehicles.available.invalidate(), utils.operations.history.invalidate(), utils.contracts.details.invalidate(), utils.accounting.invalidate(), utils.dashboard.invalidate()]); }, onError: (error) => toast.error(error.message) });
  const submit = () => {
    if (selectedContract?.status === "returned") return toast.error("لا يمكن تنفيذ أي عملية: تم استرجاع العقد وإغلاقه نهائياً");
    if (!contractNumber.trim()) return toast.error("أدخل رقم العقد الظاهر أولاً");
    if (operation === "payment" && (paymentMethod === "mixed" ? paymentTotal <= 0 || Number(cashAmount) <= 0 || Number(networkAmount) <= 0 : !amount || Number(amount) <= 0)) return toast.error(paymentMethod === "mixed" ? "أدخل مبلغ الكاش ومبلغ الشبكة" : "أدخل مبلغاً صحيحاً");
    if (operation === "extension" && (!extensionDays || Number(extensionDays) <= 0)) return toast.error("أدخل عدد أيام التمديد");
    if (operation === "extension" && extensionPaymentMethod === "mixed" && extensionPaymentTotal > 0 && (Number(extensionPaymentCashAmount) <= 0 || Number(extensionPaymentNetworkAmount) <= 0)) return toast.error("أدخل مبلغ الكاش ومبلغ الشبكة لدفعة التمديد");
    if (operation === "extension" && selectedContract && extensionPaymentTotal > 0 && extensionPaymentTotal < Math.max(0, previousOutstanding + currentCharge + excessMileageOutstanding)) return toast.error(`لا تكفي دفعة التمديد لتسوية الرصيد؛ المطلوب ${Math.max(0, previousOutstanding + currentCharge + excessMileageOutstanding).toFixed(2)} ر.س`);
    if (operation === "suspend" && !followUpDate) return toast.error("حدد التاريخ المتوقع للسداد أو إعادة التواصل");
    if (requiresMileage && !vehicleMileage) return toast.error("أدخل العداد الحالي قبل تنفيذ العملية");
    if (operation === "vehicle_swap" && !vehicleId) return toast.error("اختر السيارة البديلة");
    if (vehicleMileage && (!Number.isInteger(Number(vehicleMileage)) || Number(vehicleMileage) < 0)) return toast.error("قراءة العداد يجب أن تكون رقماً صحيحاً غير سالب");
    if (operation === "payment" && paymentReason === "extra_km" && !vehicleMileage) return toast.error("أدخل العداد الجديد عند تسجيل كيلوات إضافية");
    if (operation === "payment" && paymentReason === "international_authorization_fee" && selectedContract?.contractScope !== "international") return toast.error("رسوم التفويض الدولي متاحة للعقد الخارجي الدولي فقط");
    if (operation === "payment" && paymentException === "suspended_contract" && selectedContract?.status !== "suspended") return toast.error("نوع السداد للعقد المعلق يتطلب اختيار عقد معلق");
    if (operation === "payment" && paymentException === "justified_non_suspended" && !exceptionReason.trim()) return toast.error("أدخل سبب السداد الاستثنائي");
    const reasonText = operation === "payment" ? (paymentReason === "extra_km" ? `كيلوات إضافية؛ العداد الجديد: ${vehicleMileage}` : paymentReasonLabels[paymentReason]) : operation === "suspend" ? `سبب التعليق: ${suspensionReasonLabels[suspensionReason]}` : "";
    record.mutate({ contractNumber, operation, amount: operation === "payment" ? paymentTotal.toFixed(2) : undefined, paymentMethod: operation === "payment" ? paymentMethod : undefined, paymentCashAmount: operation === "payment" && paymentMethod === "mixed" ? Number(cashAmount).toFixed(2) : undefined, paymentNetworkAmount: operation === "payment" && paymentMethod === "mixed" ? Number(networkAmount).toFixed(2) : undefined, paymentFirstMethod: operation === "payment" && paymentMethod === "mixed" ? paymentFirstMethod : undefined, paymentSecondMethod: operation === "payment" && paymentMethod === "mixed" ? paymentSecondMethod : undefined, paymentFirstAmount: operation === "payment" && paymentMethod === "mixed" ? Number(cashAmount).toFixed(2) : undefined, paymentSecondAmount: operation === "payment" && paymentMethod === "mixed" ? Number(networkAmount).toFixed(2) : undefined, paymentReason: operation === "payment" ? paymentReason : undefined, paymentException: operation === "payment" && paymentException !== "none" ? paymentException : undefined, exceptionReason: operation === "payment" && paymentException !== "none" ? exceptionReason.trim() : undefined, extensionDays: operation === "extension" ? Number(extensionDays) : undefined, extensionPaymentAmount: operation === "extension" && extensionPaymentTotal > 0 ? extensionPaymentTotal.toFixed(2) : undefined, extensionPaymentMethod: operation === "extension" && extensionPaymentTotal > 0 ? extensionPaymentMethod : undefined, extensionPaymentCashAmount: operation === "extension" && extensionPaymentMethod === "mixed" ? Number(extensionPaymentCashAmount).toFixed(2) : undefined, extensionPaymentNetworkAmount: operation === "extension" && extensionPaymentMethod === "mixed" ? Number(extensionPaymentNetworkAmount).toFixed(2) : undefined, followUpDate: operation === "suspend" ? followUpDate : undefined, vehicleId: operation === "vehicle_swap" ? Number(vehicleId) : undefined, vehicleMileage: vehicleMileage ? Number(vehicleMileage) : undefined, details: [reasonText, details.trim()].filter(Boolean).join("؛ ") || undefined });
  };
  const Icon = operationCards.find((card) => card.value === operation)?.icon ?? Banknote;
  return <div dir="rtl" className="space-y-4">
    {location === "/contracts/suspended" && <Card className="border-0 bg-amber-50 shadow-sm"><CardContent className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="text-xs font-semibold text-amber-700">إجمالي المبالغ المستحقة للعقود المعلّقة</p><p className="mt-1 text-xs text-amber-600">هذا المبلغ مستقل عن المستحقات العامة للعقود السارية والمتأخرة.</p></div><p className="text-2xl font-black text-amber-700">{suspendedOutstanding.toFixed(2)} ر.س</p></CardContent></Card>}
    <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Icon className="h-5 w-5 text-[#139f95]" />إدارة عقد قائم</CardTitle><p className="text-xs leading-5 text-slate-400">أدخل رقم العقد، ثم اختر العملية المطلوبة وأكمل حقولها.</p></CardHeader><CardContent className="space-y-4">
      <Input value={contractNumber} onChange={(event) => setContractNumber(event.target.value)} placeholder="رقم العقد الظاهر مثل 1011" inputMode="numeric" className="min-h-12" />
      {selectedContract ? <div className="space-y-2 rounded-xl bg-[#effaf8] px-3 py-2 text-xs"><div className="grid grid-cols-2 gap-2"><span className="text-slate-500">المتبقي الحالي</span><strong className="text-left text-[#0c8f87]">{remaining?.toFixed(2)} ر.س</strong></div>{operation === "close" && closePreview && <div className="border-t border-[#cdeee9] pt-2 leading-5 text-amber-700"><p>المستحق حتى يوم الإغلاق: <strong>{closePreview.amountDueThroughClose} ر.س</strong>.</p>{closePreview.shouldRecordReturn ? <p className="mt-1 font-semibold text-[#0c8f87]">فائض مدفوع {closePreview.customerCredit} ر.س: ستُرحّل السيارة تلقائياً إلى سجل الاسترجاعات.</p> : closePreview.canClose ? <p className="mt-1 text-[#0c8f87]">لا يوجد رصيد مستحق حتى يوم الإغلاق.</p> : <p className="mt-1 font-semibold text-red-600">المتبقي حتى يوم الإغلاق {closePreview.balances.grandOutstanding} ر.س.</p>}</div>}{operation === "suspend" && suspensionPreview && <div className="border-t border-[#cdeee9] pt-2 leading-5 text-amber-700"><p>بعد التعليق سيُخصم من الإجمالي <strong>{suspensionPreview.unusedValue} ر.س</strong> مقابل <strong>{suspensionPreview.remainingDays} يوم</strong> غير مستخدم.</p><p className="mt-1 font-semibold text-[#0c8f87]">المتبقي بعد التسوية: {suspensionPreview.balances.grandOutstanding} ر.س.</p></div>}{allocation && <div className="grid grid-cols-2 gap-2 border-t border-[#cdeee9] pt-2"><span className="text-slate-500">توزيع الدفعة</span><strong className="text-left text-[#0c8f87]">{allocation.appliedToPrevious.toFixed(2)} ← {allocation.appliedToCurrent.toFixed(2)} ← {allocation.appliedToExcessMileage.toFixed(2)} ر.س</strong></div>}</div> : contractNumber.trim() && !contracts.isLoading ? <p className="text-xs text-red-600">لم يتم العثور على العقد بهذا الرقم</p> : null}
      {selectedContract?.status === "returned" && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-xs font-semibold text-rose-700">تم استرجاع هذا العقد وإغلاقه نهائياً؛ لا يمكن تنفيذ عمليات إضافية عليه.</div>}
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-3" aria-label="اختيار العملية">{operationCards.map(({ value, label, icon: CardIcon }) => <button key={value} type="button" disabled={selectedContract?.status === "returned"} onClick={() => setOperation(value)} className={`flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl border p-3 text-center text-sm font-bold transition ${operation === value ? "border-[#139f95] bg-[#effaf8] text-[#0c8f87] ring-2 ring-[#b8e7e2]" : "border-slate-200 bg-white text-slate-600 hover:border-[#8dd8d0]"}`}><CardIcon className="h-6 w-6" />{label}</button>)}</div>
      {operation === "payment" && <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value as PaymentMethod)} aria-label="طريقة الدفع" className="h-12 rounded-md border border-input bg-background px-3 text-sm"><option value="cash">كاش</option><option value="network">شبكة</option><option value="transfer">تحويل</option><option value="mixed">نصف كاش ونصف شبكة</option></select>{paymentMethod === "mixed" ? <><select value={paymentFirstMethod} onChange={(event) => setPaymentFirstMethod(event.target.value as typeof paymentFirstMethod)} aria-label="طريقة الدفعة الأولى" className="h-12 rounded-md border border-input bg-background px-3 text-sm"><option value="cash">الدفعة الأولى: كاش</option><option value="network">الدفعة الأولى: شبكة</option><option value="transfer">الدفعة الأولى: تحويل</option></select><select value={paymentSecondMethod} onChange={(event) => setPaymentSecondMethod(event.target.value as typeof paymentSecondMethod)} aria-label="طريقة الدفعة الثانية" className="h-12 rounded-md border border-input bg-background px-3 text-sm"><option value="cash">الدفعة الثانية: كاش</option><option value="network">الدفعة الثانية: شبكة</option><option value="transfer">الدفعة الثانية: تحويل</option></select><Input type="number" min="0.01" value={cashAmount} onChange={(event) => setCashAmount(event.target.value)} placeholder="مبلغ الكاش" className="min-h-12" /><Input type="number" min="0.01" value={networkAmount} onChange={(event) => setNetworkAmount(event.target.value)} placeholder="مبلغ الشبكة" className="min-h-12" /></> : <Input type="number" min="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="المبلغ" className="min-h-12" />}</div>}
      {operation === "payment" && <div className="grid gap-3 rounded-xl border border-amber-200 bg-amber-50 p-3"><select value={paymentException} onChange={(event) => setPaymentException(event.target.value as typeof paymentException)} aria-label="نوع السداد" className="h-12 rounded-md border border-input bg-white px-3 text-sm"><option value="none">سداد العقد الحالي</option>{selectedContract?.status === "suspended" && <option value="suspended_contract">سداد عقد معلّق</option>}<option value="justified_non_suspended">سداد مبرر لعقد غير معلّق</option></select>{paymentException === "justified_non_suspended" && <Input value={exceptionReason} onChange={(event) => setExceptionReason(event.target.value)} placeholder="سبب السداد الاستثنائي" className="min-h-12 bg-white" />}</div>}
      {requiresMileage && <Input type="number" min="0" value={vehicleMileage} onChange={(event) => setVehicleMileage(event.target.value)} placeholder="العداد الحالي عند تنفيذ العملية" className="min-h-12" />}
      {operation === "payment" || operation === "additional_fee" ? <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><select value={paymentReason} onChange={(event) => setPaymentReason(event.target.value as PaymentReason)} aria-label="سبب الدفعة" className="h-12 rounded-md border border-input bg-background px-3 text-sm">{paymentReasonOptions.filter((option) => !("internationalOnly" in option) || selectedContract?.contractScope === "international").map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{paymentReason === "extra_km" && <Input value={vehicleMileage} onChange={(event) => setVehicleMileage(event.target.value)} placeholder="العداد الجديد" className="min-h-12" />}</div> : null}
      {operation === "suspend" && <><select value={suspensionReason} onChange={(event) => setSuspensionReason(event.target.value as SuspensionReason)} className="h-12 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="financial_default">تعثر أو تأخر مالي</option>{suspensionReasonOptions.filter((option) => option.value !== "financial_default").map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><div className="rounded-xl border border-amber-200 bg-amber-50 p-3"><label className="block text-xs font-semibold text-amber-800" htmlFor="contract-follow-up-date">التاريخ المتوقع للسداد أو إعادة التواصل</label><Input id="contract-follow-up-date" type="date" value={followUpDate} onChange={(event) => setFollowUpDate(event.target.value)} className="mt-2 min-h-12 border-amber-200 bg-white" /></div></>}
      {operation === "extension" && <div className="space-y-3 rounded-xl border border-[#cdeee9] bg-[#effaf8] p-3"><Input value={extensionDays} onChange={(event) => setExtensionDays(event.target.value)} placeholder="عدد أيام التمديد" className="min-h-12 bg-white" />{selectedContract && <div className="grid grid-cols-2 gap-2 text-xs"><span className="text-slate-500">المتبقي السابق</span><strong className="text-left">{previousOutstanding.toFixed(2)} ر.س</strong><span className="text-slate-500">التأخير / المتبقي الحالي</span><strong className="text-left text-red-600">{currentCharge.toFixed(2)} ر.س</strong></div>}<p className="text-xs text-amber-700">لا يُسمح بالتمديد مع وجود متأخرات إلا بعد سدادها بالكامل.</p><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><select value={extensionPaymentMethod} onChange={(event) => setExtensionPaymentMethod(event.target.value as PaymentMethod)} className="h-12 rounded-md border border-input bg-white px-3 text-sm"><option value="cash">كاش</option><option value="network">شبكة</option><option value="transfer">تحويل</option><option value="mixed">نصف كاش ونصف شبكة</option></select>{extensionPaymentMethod === "mixed" ? <><Input type="number" value={extensionPaymentCashAmount} onChange={(event) => setExtensionPaymentCashAmount(event.target.value)} placeholder="كاش التسوية" className="min-h-12 bg-white" /><Input type="number" value={extensionPaymentNetworkAmount} onChange={(event) => setExtensionPaymentNetworkAmount(event.target.value)} placeholder="شبكة التسوية" className="min-h-12 bg-white" /></> : <Input type="number" value={extensionPaymentAmount} onChange={(event) => setExtensionPaymentAmount(event.target.value)} placeholder="مبلغ تسوية المتأخرات" className="min-h-12 bg-white" />}</div>{extensionAllocation && <p className="text-xs font-semibold text-[#0c8f87]">تخصيص الدفعة: السابق {extensionAllocation.appliedToPrevious.toFixed(2)} ر.س، ثم الحالي {extensionAllocation.appliedToCurrent.toFixed(2)} ر.س.</p>}</div>}
      {operation === "vehicle_swap" && <div className="flex items-center gap-2"><CarFront className="h-5 w-5 shrink-0 text-[#139f95]" /><select value={vehicleId} onChange={(event) => setVehicleId(event.target.value)} className="h-12 min-w-0 flex-1 rounded-md border border-input bg-background px-3 text-sm"><option value="">اختر السيارة البديلة المتاحة</option>{vehicles.data?.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.make} {vehicle.model} — {vehicle.plateNumber}</option>)}</select></div>}
      <Textarea disabled={selectedContract?.status === "returned"} value={details} onChange={(event) => setDetails(event.target.value)} placeholder="ملاحظات العملية (اختياري)" className="min-h-24 resize-y" />
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Button onClick={submit} disabled={record.isPending || selectedContract?.status === "returned"} className="min-h-12 bg-[#139f95] font-bold hover:bg-[#0d938b]">{record.isPending ? "جارٍ حفظ العملية..." : "حفظ العملية"}</Button><Button type="button" variant="outline" onClick={resetForm} disabled={record.isPending} className="min-h-12">إلغاء</Button></div>
    </CardContent></Card>
  </div>;
}
